quarkus:
  debug:
    port: 5005
  datasource:
    url: jdbc:postgresql://{DB_HOST}:{DB_PORT}/{DB_NAME}
    driver: org.postgresql.Driver
    username: {DB_USERNAME}
    password: {DB_PASSWORD}
  hibernate-orm:
    database:
      generation: update
  swagger-ui:
    path: /swagger
    always-include: true

firebase:
  database-url: {FIREBASE_DATABASE_URL}
  location-path: /serviceAccountKey.json
