quarkus:
  debug:
    port: 5005
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:quarkus}
    driver: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
  hibernate-orm:
    database:
      generation: update
  swagger-ui:
    path: /swagger
    always-include: true

firebase:
  database-url: ${FIREBASE_DATABASE_URL:https://fir-auth-learn-5ed0b.firebaseio.com}
  location-path: /serviceAccountKey.json
